// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows
package win_sc

import (
	"encoding/xml"
	"github.com/complianceascode/librescap/pkg/scap/models/oval"
	"github.com/complianceascode/librescap/pkg/scap/models/oval_sc"
)

// Element
type AccesstokenItem struct {
	XMLName xml.Name `xml:accesstoken_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	SecurityPrinciple *oval_sc.EntityItemStringType `xml:"security_principle"`

	Seassignprimarytokenprivilege *oval_sc.EntityItemBoolType `xml:"seassignprimarytokenprivilege"`

	Seauditprivilege *oval_sc.EntityItemBoolType `xml:"seauditprivilege"`

	Sebackupprivilege *oval_sc.EntityItemBoolType `xml:"sebackupprivilege"`

	Sechangenotifyprivilege *oval_sc.EntityItemBoolType `xml:"sechangenotifyprivilege"`

	Secreateglobalprivilege *oval_sc.EntityItemBoolType `xml:"secreateglobalprivilege"`

	Secreatepagefileprivilege *oval_sc.EntityItemBoolType `xml:"secreatepagefileprivilege"`

	Secreatepermanentprivilege *oval_sc.EntityItemBoolType `xml:"secreatepermanentprivilege"`

	Secreatesymboliclinkprivilege *oval_sc.EntityItemBoolType `xml:"secreatesymboliclinkprivilege"`

	Secreatetokenprivilege *oval_sc.EntityItemBoolType `xml:"secreatetokenprivilege"`

	Sedebugprivilege *oval_sc.EntityItemBoolType `xml:"sedebugprivilege"`

	Seenabledelegationprivilege *oval_sc.EntityItemBoolType `xml:"seenabledelegationprivilege"`

	Seimpersonateprivilege *oval_sc.EntityItemBoolType `xml:"seimpersonateprivilege"`

	Seincreasebasepriorityprivilege *oval_sc.EntityItemBoolType `xml:"seincreasebasepriorityprivilege"`

	Seincreasequotaprivilege *oval_sc.EntityItemBoolType `xml:"seincreasequotaprivilege"`

	Seincreaseworkingsetprivilege *oval_sc.EntityItemBoolType `xml:"seincreaseworkingsetprivilege"`

	Seloaddriverprivilege *oval_sc.EntityItemBoolType `xml:"seloaddriverprivilege"`

	Selockmemoryprivilege *oval_sc.EntityItemBoolType `xml:"selockmemoryprivilege"`

	Semachineaccountprivilege *oval_sc.EntityItemBoolType `xml:"semachineaccountprivilege"`

	Semanagevolumeprivilege *oval_sc.EntityItemBoolType `xml:"semanagevolumeprivilege"`

	Seprofilesingleprocessprivilege *oval_sc.EntityItemBoolType `xml:"seprofilesingleprocessprivilege"`

	Serelabelprivilege *oval_sc.EntityItemBoolType `xml:"serelabelprivilege"`

	Seremoteshutdownprivilege *oval_sc.EntityItemBoolType `xml:"seremoteshutdownprivilege"`

	Serestoreprivilege *oval_sc.EntityItemBoolType `xml:"serestoreprivilege"`

	Sesecurityprivilege *oval_sc.EntityItemBoolType `xml:"sesecurityprivilege"`

	Seshutdownprivilege *oval_sc.EntityItemBoolType `xml:"seshutdownprivilege"`

	Sesyncagentprivilege *oval_sc.EntityItemBoolType `xml:"sesyncagentprivilege"`

	Sesystemenvironmentprivilege *oval_sc.EntityItemBoolType `xml:"sesystemenvironmentprivilege"`

	Sesystemprofileprivilege *oval_sc.EntityItemBoolType `xml:"sesystemprofileprivilege"`

	Sesystemtimeprivilege *oval_sc.EntityItemBoolType `xml:"sesystemtimeprivilege"`

	Setakeownershipprivilege *oval_sc.EntityItemBoolType `xml:"setakeownershipprivilege"`

	Setcbprivilege *oval_sc.EntityItemBoolType `xml:"setcbprivilege"`

	Setimezoneprivilege *oval_sc.EntityItemBoolType `xml:"setimezoneprivilege"`

	Seundockprivilege *oval_sc.EntityItemBoolType `xml:"seundockprivilege"`

	Seunsolicitedinputprivilege *oval_sc.EntityItemBoolType `xml:"seunsolicitedinputprivilege"`

	Sebatchlogonright *oval_sc.EntityItemBoolType `xml:"sebatchlogonright"`

	Seinteractivelogonright *oval_sc.EntityItemBoolType `xml:"seinteractivelogonright"`

	Senetworklogonright *oval_sc.EntityItemBoolType `xml:"senetworklogonright"`

	Seremoteinteractivelogonright *oval_sc.EntityItemBoolType `xml:"seremoteinteractivelogonright"`

	Seservicelogonright *oval_sc.EntityItemBoolType `xml:"seservicelogonright"`

	SedenybatchLogonright *oval_sc.EntityItemBoolType `xml:"sedenybatchLogonright"`

	Sedenyinteractivelogonright *oval_sc.EntityItemBoolType `xml:"sedenyinteractivelogonright"`

	Sedenynetworklogonright *oval_sc.EntityItemBoolType `xml:"sedenynetworklogonright"`

	SedenyremoteInteractivelogonright *oval_sc.EntityItemBoolType `xml:"sedenyremoteInteractivelogonright"`

	Sedenyservicelogonright *oval_sc.EntityItemBoolType `xml:"sedenyservicelogonright"`

	Setrustedcredmanaccessnameright *oval_sc.EntityItemBoolType `xml:"setrustedcredmanaccessnameright"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type ActivedirectoryItem struct {
	XMLName xml.Name `xml:activedirectory_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	NamingContext *EntityItemNamingContextType `xml:"naming_context"`

	RelativeDn *oval_sc.EntityItemStringType `xml:"relative_dn"`

	Attribute *oval_sc.EntityItemStringType `xml:"attribute"`

	ObjectClass *oval_sc.EntityItemStringType `xml:"object_class"`

	Adstype *EntityItemAdstypeType `xml:"adstype"`

	Value []oval_sc.EntityItemAnySimpleType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type Activedirectory57Item struct {
	XMLName xml.Name `xml:activedirectory57_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	NamingContext *EntityItemNamingContextType `xml:"naming_context"`

	RelativeDn *oval_sc.EntityItemStringType `xml:"relative_dn"`

	Attribute *oval_sc.EntityItemStringType `xml:"attribute"`

	ObjectClass *oval_sc.EntityItemStringType `xml:"object_class"`

	Adstype *EntityItemAdstypeType `xml:"adstype"`

	Value []oval_sc.EntityItemRecordType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type AuditeventpolicyItem struct {
	XMLName xml.Name `xml:auditeventpolicy_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	AccountLogon *EntityItemAuditType `xml:"account_logon"`

	AccountManagement *EntityItemAuditType `xml:"account_management"`

	DetailedTracking *EntityItemAuditType `xml:"detailed_tracking"`

	DirectoryServiceAccess *EntityItemAuditType `xml:"directory_service_access"`

	Logon *EntityItemAuditType `xml:"logon"`

	ObjectAccess *EntityItemAuditType `xml:"object_access"`

	PolicyChange *EntityItemAuditType `xml:"policy_change"`

	PrivilegeUse *EntityItemAuditType `xml:"privilege_use"`

	System *EntityItemAuditType `xml:"system"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type AuditeventpolicysubcategoriesItem struct {
	XMLName xml.Name `xml:auditeventpolicysubcategories_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	CredentialValidation *EntityItemAuditType `xml:"credential_validation"`

	KerberosAuthenticationService *EntityItemAuditType `xml:"kerberos_authentication_service"`

	KerberosServiceTicketOperations *EntityItemAuditType `xml:"kerberos_service_ticket_operations"`

	KerberosTicketEvents *EntityItemAuditType `xml:"kerberos_ticket_events"`

	OtherAccountLogonEvents *EntityItemAuditType `xml:"other_account_logon_events"`

	ApplicationGroupManagement *EntityItemAuditType `xml:"application_group_management"`

	ComputerAccountManagement *EntityItemAuditType `xml:"computer_account_management"`

	DistributionGroupManagement *EntityItemAuditType `xml:"distribution_group_management"`

	OtherAccountManagementEvents *EntityItemAuditType `xml:"other_account_management_events"`

	SecurityGroupManagement *EntityItemAuditType `xml:"security_group_management"`

	UserAccountManagement *EntityItemAuditType `xml:"user_account_management"`

	DpapiActivity *EntityItemAuditType `xml:"dpapi_activity"`

	ProcessCreation *EntityItemAuditType `xml:"process_creation"`

	ProcessTermination *EntityItemAuditType `xml:"process_termination"`

	RpcEvents *EntityItemAuditType `xml:"rpc_events"`

	DirectoryServiceAccess *EntityItemAuditType `xml:"directory_service_access"`

	DirectoryServiceChanges *EntityItemAuditType `xml:"directory_service_changes"`

	DirectoryServiceReplication *EntityItemAuditType `xml:"directory_service_replication"`

	DetailedDirectoryServiceReplication *EntityItemAuditType `xml:"detailed_directory_service_replication"`

	AccountLockout *EntityItemAuditType `xml:"account_lockout"`

	IpsecExtendedMode *EntityItemAuditType `xml:"ipsec_extended_mode"`

	IpsecMainMode *EntityItemAuditType `xml:"ipsec_main_mode"`

	IpsecQuickMode *EntityItemAuditType `xml:"ipsec_quick_mode"`

	Logoff *EntityItemAuditType `xml:"logoff"`

	Logon *EntityItemAuditType `xml:"logon"`

	NetworkPolicyServer *EntityItemAuditType `xml:"network_policy_server"`

	OtherLogonLogoffEvents *EntityItemAuditType `xml:"other_logon_logoff_events"`

	SpecialLogon *EntityItemAuditType `xml:"special_logon"`

	LogonClaims *EntityItemAuditType `xml:"logon_claims"`

	ApplicationGenerated *EntityItemAuditType `xml:"application_generated"`

	CertificationServices *EntityItemAuditType `xml:"certification_services"`

	DetailedFileShare *EntityItemAuditType `xml:"detailed_file_share"`

	FileShare *EntityItemAuditType `xml:"file_share"`

	FileSystem *EntityItemAuditType `xml:"file_system"`

	FilteringPlatformConnection *EntityItemAuditType `xml:"filtering_platform_connection"`

	FilteringPlatformPacketDrop *EntityItemAuditType `xml:"filtering_platform_packet_drop"`

	HandleManipulation *EntityItemAuditType `xml:"handle_manipulation"`

	KernelObject *EntityItemAuditType `xml:"kernel_object"`

	OtherObjectAccessEvents *EntityItemAuditType `xml:"other_object_access_events"`

	Registry *EntityItemAuditType `xml:"registry"`

	Sam *EntityItemAuditType `xml:"sam"`

	RemovableStorage *EntityItemAuditType `xml:"removable_storage"`

	CentralAccessPolicyStaging *EntityItemAuditType `xml:"central_access_policy_staging"`

	AuditPolicyChange *EntityItemAuditType `xml:"audit_policy_change"`

	AuthenticationPolicyChange *EntityItemAuditType `xml:"authentication_policy_change"`

	AuthorizationPolicyChange *EntityItemAuditType `xml:"authorization_policy_change"`

	FilteringPlatformPolicyChange *EntityItemAuditType `xml:"filtering_platform_policy_change"`

	MpssvcRuleLevelPolicyChange *EntityItemAuditType `xml:"mpssvc_rule_level_policy_change"`

	OtherPolicyChangeEvents *EntityItemAuditType `xml:"other_policy_change_events"`

	NonSensitivePrivilegeUse *EntityItemAuditType `xml:"non_sensitive_privilege_use"`

	OtherPrivilegeUseEvents *EntityItemAuditType `xml:"other_privilege_use_events"`

	SensitivePrivilegeUse *EntityItemAuditType `xml:"sensitive_privilege_use"`

	IpsecDriver *EntityItemAuditType `xml:"ipsec_driver"`

	OtherSystemEvents *EntityItemAuditType `xml:"other_system_events"`

	SecurityStateChange *EntityItemAuditType `xml:"security_state_change"`

	SecuritySystemExtension *EntityItemAuditType `xml:"security_system_extension"`

	SystemIntegrity *EntityItemAuditType `xml:"system_integrity"`

	GroupMembership *EntityItemAuditType `xml:"group_membership"`

	PnpActivity *EntityItemAuditType `xml:"pnp_activity"`

	UserDeviceClaims *EntityItemAuditType `xml:"user_device_claims"`

	AuditDetailedtrackingTokenrightadjusted *EntityItemAuditType `xml:"audit_detailedtracking_tokenrightadjusted"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type CmdletItem struct {
	XMLName xml.Name `xml:cmdlet_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	ModuleName *oval_sc.EntityItemStringType `xml:"module_name"`

	ModuleId *EntityItemGUIDType `xml:"module_id"`

	ModuleVersion *oval_sc.EntityItemVersionType `xml:"module_version"`

	Verb *EntityItemCmdletVerbType `xml:"verb"`

	Noun *oval_sc.EntityItemStringType `xml:"noun"`

	Parameters *oval_sc.EntityItemRecordType `xml:"parameters"`

	Select *oval_sc.EntityItemRecordType `xml:"select"`

	Value []oval_sc.EntityItemRecordType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type DnscacheItem struct {
	XMLName xml.Name `xml:dnscache_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	DomainName *oval_sc.EntityItemStringType `xml:"domain_name"`

	Ttl *oval_sc.EntityItemIntType `xml:"ttl"`

	IpAddress []oval_sc.EntityItemIPAddressStringType `xml:"ip_address"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type FileItem struct {
	XMLName xml.Name `xml:file_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Filepath *oval_sc.EntityItemStringType `xml:"filepath"`

	Path *oval_sc.EntityItemStringType `xml:"path"`

	Filename *oval_sc.EntityItemStringType `xml:"filename"`

	Owner *oval_sc.EntityItemStringType `xml:"owner"`

	Size *oval_sc.EntityItemIntType `xml:"size"`

	ATime *oval_sc.EntityItemIntType `xml:"a_time"`

	CTime *oval_sc.EntityItemIntType `xml:"c_time"`

	MTime *oval_sc.EntityItemIntType `xml:"m_time"`

	MsChecksum *oval_sc.EntityItemStringType `xml:"ms_checksum"`

	Version *oval_sc.EntityItemVersionType `xml:"version"`

	Type *EntityItemFileTypeType `xml:"type"`

	Attribute []EntityItemFileAttributeType `xml:"attribute"`

	DevelopmentClass *oval_sc.EntityItemStringType `xml:"development_class"`

	Company *oval_sc.EntityItemStringType `xml:"company"`

	InternalName *oval_sc.EntityItemStringType `xml:"internal_name"`

	Language *oval_sc.EntityItemStringType `xml:"language"`

	OriginalFilename *oval_sc.EntityItemStringType `xml:"original_filename"`

	ProductName *oval_sc.EntityItemStringType `xml:"product_name"`

	ProductVersion *FileItemProductVersion `xml:"product_version"`

	WindowsView *EntityItemWindowsViewType `xml:"windows_view"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type FileauditedpermissionsItem struct {
	XMLName xml.Name `xml:fileauditedpermissions_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Filepath *oval_sc.EntityItemStringType `xml:"filepath"`

	Path *oval_sc.EntityItemStringType `xml:"path"`

	Filename *oval_sc.EntityItemStringType `xml:"filename"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	TrusteeName *oval_sc.EntityItemStringType `xml:"trustee_name"`

	StandardDelete *EntityItemAuditType `xml:"standard_delete"`

	StandardReadControl *EntityItemAuditType `xml:"standard_read_control"`

	StandardWriteDac *EntityItemAuditType `xml:"standard_write_dac"`

	StandardWriteOwner *EntityItemAuditType `xml:"standard_write_owner"`

	StandardSynchronize *EntityItemAuditType `xml:"standard_synchronize"`

	AccessSystemSecurity *EntityItemAuditType `xml:"access_system_security"`

	GenericRead *EntityItemAuditType `xml:"generic_read"`

	GenericWrite *EntityItemAuditType `xml:"generic_write"`

	GenericExecute *EntityItemAuditType `xml:"generic_execute"`

	GenericAll *EntityItemAuditType `xml:"generic_all"`

	FileReadData *EntityItemAuditType `xml:"file_read_data"`

	FileWriteData *EntityItemAuditType `xml:"file_write_data"`

	FileAppendData *EntityItemAuditType `xml:"file_append_data"`

	FileReadEa *EntityItemAuditType `xml:"file_read_ea"`

	FileWriteEa *EntityItemAuditType `xml:"file_write_ea"`

	FileExecute *EntityItemAuditType `xml:"file_execute"`

	FileDeleteChild *EntityItemAuditType `xml:"file_delete_child"`

	FileReadAttributes *EntityItemAuditType `xml:"file_read_attributes"`

	FileWriteAttributes *EntityItemAuditType `xml:"file_write_attributes"`

	WindowsView *EntityItemWindowsViewType `xml:"windows_view"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type FileeffectiverightsItem struct {
	XMLName xml.Name `xml:fileeffectiverights_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Filepath *oval_sc.EntityItemStringType `xml:"filepath"`

	Path *oval_sc.EntityItemStringType `xml:"path"`

	Filename *oval_sc.EntityItemStringType `xml:"filename"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	TrusteeName *oval_sc.EntityItemStringType `xml:"trustee_name"`

	StandardDelete *oval_sc.EntityItemBoolType `xml:"standard_delete"`

	StandardReadControl *oval_sc.EntityItemBoolType `xml:"standard_read_control"`

	StandardWriteDac *oval_sc.EntityItemBoolType `xml:"standard_write_dac"`

	StandardWriteOwner *oval_sc.EntityItemBoolType `xml:"standard_write_owner"`

	StandardSynchronize *oval_sc.EntityItemBoolType `xml:"standard_synchronize"`

	AccessSystemSecurity *oval_sc.EntityItemBoolType `xml:"access_system_security"`

	GenericRead *oval_sc.EntityItemBoolType `xml:"generic_read"`

	GenericWrite *oval_sc.EntityItemBoolType `xml:"generic_write"`

	GenericExecute *oval_sc.EntityItemBoolType `xml:"generic_execute"`

	GenericAll *oval_sc.EntityItemBoolType `xml:"generic_all"`

	FileReadData *oval_sc.EntityItemBoolType `xml:"file_read_data"`

	FileWriteData *oval_sc.EntityItemBoolType `xml:"file_write_data"`

	FileAppendData *oval_sc.EntityItemBoolType `xml:"file_append_data"`

	FileReadEa *oval_sc.EntityItemBoolType `xml:"file_read_ea"`

	FileWriteEa *oval_sc.EntityItemBoolType `xml:"file_write_ea"`

	FileExecute *oval_sc.EntityItemBoolType `xml:"file_execute"`

	FileDeleteChild *oval_sc.EntityItemBoolType `xml:"file_delete_child"`

	FileReadAttributes *oval_sc.EntityItemBoolType `xml:"file_read_attributes"`

	FileWriteAttributes *oval_sc.EntityItemBoolType `xml:"file_write_attributes"`

	WindowsView *EntityItemWindowsViewType `xml:"windows_view"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type GroupItem struct {
	XMLName xml.Name `xml:group_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Group *oval_sc.EntityItemStringType `xml:"group"`

	User []oval_sc.EntityItemStringType `xml:"user"`

	Subgroup []oval_sc.EntityItemStringType `xml:"subgroup"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type GroupSidItem struct {
	XMLName xml.Name `xml:group_sid_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	GroupSid *oval_sc.EntityItemStringType `xml:"group_sid"`

	UserSid []oval_sc.EntityItemStringType `xml:"user_sid"`

	SubgroupSid []oval_sc.EntityItemStringType `xml:"subgroup_sid"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type InterfaceItem struct {
	XMLName xml.Name `xml:interface_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Name *oval_sc.EntityItemStringType `xml:"name"`

	Index *oval_sc.EntityItemIntType `xml:"index"`

	Type *EntityItemInterfaceTypeType `xml:"type"`

	HardwareAddr *oval_sc.EntityItemStringType `xml:"hardware_addr"`

	InetAddr *oval_sc.EntityItemIPAddressStringType `xml:"inet_addr"`

	BroadcastAddr *oval_sc.EntityItemIPAddressStringType `xml:"broadcast_addr"`

	Netmask *oval_sc.EntityItemIPAddressStringType `xml:"netmask"`

	AddrType []EntityItemAddrTypeType `xml:"addr_type"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type JunctionItem struct {
	XMLName xml.Name `xml:junction_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Path oval_sc.EntityItemStringType `xml:"path"`

	CanonicalPath oval_sc.EntityItemStringType `xml:"canonical_path"`

	WindowsView *EntityItemWindowsViewType `xml:"windows_view"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type LicenseItem struct {
	XMLName xml.Name `xml:license_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Name *oval_sc.EntityItemStringType `xml:"name"`

	Type *EntityItemRegistryTypeType `xml:"type"`

	Value *oval_sc.EntityItemAnySimpleType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type LockoutpolicyItem struct {
	XMLName xml.Name `xml:lockoutpolicy_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	ForceLogoff *oval_sc.EntityItemIntType `xml:"force_logoff"`

	LockoutDuration *oval_sc.EntityItemIntType `xml:"lockout_duration"`

	LockoutObservationWindow *oval_sc.EntityItemIntType `xml:"lockout_observation_window"`

	LockoutThreshold *oval_sc.EntityItemIntType `xml:"lockout_threshold"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type MetabaseItem struct {
	XMLName xml.Name `xml:metabase_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Key *oval_sc.EntityItemStringType `xml:"key"`

	IdElm *oval_sc.EntityItemIntType `xml:"id"`

	Name *oval_sc.EntityItemStringType `xml:"name"`

	UserType *oval_sc.EntityItemStringType `xml:"user_type"`

	DataType *oval_sc.EntityItemStringType `xml:"data_type"`

	Data []oval_sc.EntityItemAnySimpleType `xml:"data"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type NtuserItem struct {
	XMLName xml.Name `xml:ntuser_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Key *oval_sc.EntityItemStringType `xml:"key"`

	Name *oval_sc.EntityItemStringType `xml:"name"`

	Sid *oval_sc.EntityItemStringType `xml:"sid"`

	Username *oval_sc.EntityItemStringType `xml:"username"`

	AccountType *EntityItemNTUserAccountTypeType `xml:"account_type"`

	LoggedOn *oval_sc.EntityItemBoolType `xml:"logged_on"`

	Enabled *oval_sc.EntityItemBoolType `xml:"enabled"`

	DateModified *oval_sc.EntityItemIntType `xml:"date_modified"`

	DaysSinceModified *oval_sc.EntityItemIntType `xml:"days_since_modified"`

	Filepath *oval_sc.EntityItemStringType `xml:"filepath"`

	LastWriteTime *oval_sc.EntityItemIntType `xml:"last_write_time"`

	Type *EntityItemRegistryTypeType `xml:"type"`

	Value []oval_sc.EntityItemAnySimpleType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type PasswordpolicyItem struct {
	XMLName xml.Name `xml:passwordpolicy_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	MaxPasswdAge *oval_sc.EntityItemIntType `xml:"max_passwd_age"`

	MinPasswdAge *oval_sc.EntityItemIntType `xml:"min_passwd_age"`

	MinPasswdLen *oval_sc.EntityItemIntType `xml:"min_passwd_len"`

	PasswordHistLen *oval_sc.EntityItemIntType `xml:"password_hist_len"`

	PasswordComplexity *oval_sc.EntityItemBoolType `xml:"password_complexity"`

	ReversibleEncryption *oval_sc.EntityItemBoolType `xml:"reversible_encryption"`

	AnonymousNameLookup *oval_sc.EntityItemBoolType `xml:"anonymous_name_lookup"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type PeheaderItem struct {
	XMLName xml.Name `xml:peheader_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Filepath *oval_sc.EntityItemStringType `xml:"filepath"`

	Path *oval_sc.EntityItemStringType `xml:"path"`

	Filename *oval_sc.EntityItemStringType `xml:"filename"`

	HeaderSignature *oval_sc.EntityItemStringType `xml:"header_signature"`

	TargetMachineType *EntityItemPeTargetMachineType `xml:"target_machine_type"`

	NumberOfSections *oval_sc.EntityItemIntType `xml:"number_of_sections"`

	TimeDateStamp *oval_sc.EntityItemIntType `xml:"time_date_stamp"`

	PointerToSymbolTable *oval_sc.EntityItemIntType `xml:"pointer_to_symbol_table"`

	NumberOfSymbols *oval_sc.EntityItemIntType `xml:"number_of_symbols"`

	SizeOfOptionalHeader *oval_sc.EntityItemIntType `xml:"size_of_optional_header"`

	ImageFileRelocsStripped *oval_sc.EntityItemBoolType `xml:"image_file_relocs_stripped"`

	ImageFileExecutableImage *oval_sc.EntityItemBoolType `xml:"image_file_executable_image"`

	ImageFileLineNumsStripped *oval_sc.EntityItemBoolType `xml:"image_file_line_nums_stripped"`

	ImageFileLocalSymsStripped *oval_sc.EntityItemBoolType `xml:"image_file_local_syms_stripped"`

	ImageFileAggresiveWsTrim *oval_sc.EntityItemBoolType `xml:"image_file_aggresive_ws_trim"`

	ImageFileLargeAddressAware *oval_sc.EntityItemBoolType `xml:"image_file_large_address_aware"`

	ImageFile16bitMachine *oval_sc.EntityItemBoolType `xml:"image_file_16bit_machine"`

	ImageFileBytesReversedLo *oval_sc.EntityItemBoolType `xml:"image_file_bytes_reversed_lo"`

	ImageFile32bitMachine *oval_sc.EntityItemBoolType `xml:"image_file_32bit_machine"`

	ImageFileDebugStripped *oval_sc.EntityItemBoolType `xml:"image_file_debug_stripped"`

	ImageFileRemovableRunFromSwap *oval_sc.EntityItemBoolType `xml:"image_file_removable_run_from_swap"`

	ImageFileSystem *oval_sc.EntityItemBoolType `xml:"image_file_system"`

	ImageFileDll *oval_sc.EntityItemBoolType `xml:"image_file_dll"`

	ImageFileUpSystemOnly *oval_sc.EntityItemBoolType `xml:"image_file_up_system_only"`

	ImageFileBytesReveresedHi *oval_sc.EntityItemBoolType `xml:"image_file_bytes_reveresed_hi"`

	MagicNumber *oval_sc.EntityItemIntType `xml:"magic_number"`

	MajorLinkerVersion *oval_sc.EntityItemIntType `xml:"major_linker_version"`

	MinorLinkerVersion *oval_sc.EntityItemIntType `xml:"minor_linker_version"`

	SizeOfCode *oval_sc.EntityItemIntType `xml:"size_of_code"`

	SizeOfInitializedData *oval_sc.EntityItemIntType `xml:"size_of_initialized_data"`

	SizeOfUninitializedData *oval_sc.EntityItemIntType `xml:"size_of_uninitialized_data"`

	AddressOfEntryPoint *oval_sc.EntityItemIntType `xml:"address_of_entry_point"`

	BaseOfCode *oval_sc.EntityItemIntType `xml:"base_of_code"`

	BaseOfData *oval_sc.EntityItemIntType `xml:"base_of_data"`

	ImageBaseAddress *oval_sc.EntityItemIntType `xml:"image_base_address"`

	SectionAlignment *oval_sc.EntityItemIntType `xml:"section_alignment"`

	FileAlignment *oval_sc.EntityItemIntType `xml:"file_alignment"`

	MajorOperatingSystemVersion *oval_sc.EntityItemIntType `xml:"major_operating_system_version"`

	MinorOperatingSystemVersion *oval_sc.EntityItemIntType `xml:"minor_operating_system_version"`

	MajorImageVersion *oval_sc.EntityItemIntType `xml:"major_image_version"`

	MinorImageVersion *oval_sc.EntityItemIntType `xml:"minor_image_version"`

	MajorSubsystemVersion *oval_sc.EntityItemIntType `xml:"major_subsystem_version"`

	MinorSusbsystemVersion *oval_sc.EntityItemIntType `xml:"minor_susbsystem_version"`

	SizeOfImage *oval_sc.EntityItemIntType `xml:"size_of_image"`

	SizeOfHeaders *oval_sc.EntityItemIntType `xml:"size_of_headers"`

	Checksum *oval_sc.EntityItemIntType `xml:"checksum"`

	Subsystem *EntityItemPeSubsystemType `xml:"subsystem"`

	DllCharacteristics []oval_sc.EntityItemIntType `xml:"dll_characteristics"`

	SizeOfStackReserve *oval_sc.EntityItemIntType `xml:"size_of_stack_reserve"`

	SizeOfStackCommit *oval_sc.EntityItemIntType `xml:"size_of_stack_commit"`

	SizeOfHeapReserve *oval_sc.EntityItemIntType `xml:"size_of_heap_reserve"`

	SizeOfHeapCommit *oval_sc.EntityItemIntType `xml:"size_of_heap_commit"`

	LoaderFlags *oval_sc.EntityItemIntType `xml:"loader_flags"`

	NumberOfRvaAndSizes *oval_sc.EntityItemIntType `xml:"number_of_rva_and_sizes"`

	RealNumberOfDirectoryEntries *oval_sc.EntityItemIntType `xml:"real_number_of_directory_entries"`

	WindowsView *EntityItemWindowsViewType `xml:"windows_view"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type PortItem struct {
	XMLName xml.Name `xml:port_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	LocalAddress *oval_sc.EntityItemIPAddressStringType `xml:"local_address"`

	LocalPort *oval_sc.EntityItemIntType `xml:"local_port"`

	Protocol *EntityItemProtocolType `xml:"protocol"`

	Pid *oval_sc.EntityItemIntType `xml:"pid"`

	ForeignAddress *oval_sc.EntityItemIPAddressStringType `xml:"foreign_address"`

	ForeignPort *oval_sc.EntityItemStringType `xml:"foreign_port"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type PrintereffectiverightsItem struct {
	XMLName xml.Name `xml:printereffectiverights_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	PrinterName *oval_sc.EntityItemStringType `xml:"printer_name"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	StandardDelete *oval_sc.EntityItemBoolType `xml:"standard_delete"`

	StandardReadControl *oval_sc.EntityItemBoolType `xml:"standard_read_control"`

	StandardWriteDac *oval_sc.EntityItemBoolType `xml:"standard_write_dac"`

	StandardWriteOwner *oval_sc.EntityItemBoolType `xml:"standard_write_owner"`

	StandardSynchronize *oval_sc.EntityItemBoolType `xml:"standard_synchronize"`

	AccessSystemSecurity *oval_sc.EntityItemBoolType `xml:"access_system_security"`

	GenericRead *oval_sc.EntityItemBoolType `xml:"generic_read"`

	GenericWrite *oval_sc.EntityItemBoolType `xml:"generic_write"`

	GenericExecute *oval_sc.EntityItemBoolType `xml:"generic_execute"`

	GenericAll *oval_sc.EntityItemBoolType `xml:"generic_all"`

	PrinterAccessAdminister *oval_sc.EntityItemBoolType `xml:"printer_access_administer"`

	PrinterAccessUse *oval_sc.EntityItemBoolType `xml:"printer_access_use"`

	JobAccessAdminister *oval_sc.EntityItemBoolType `xml:"job_access_administer"`

	JobAccessRead *oval_sc.EntityItemBoolType `xml:"job_access_read"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type ProcessItem struct {
	XMLName xml.Name `xml:process_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	CommandLine *oval_sc.EntityItemStringType `xml:"command_line"`

	Pid *oval_sc.EntityItemIntType `xml:"pid"`

	Ppid *oval_sc.EntityItemIntType `xml:"ppid"`

	Priority *ProcessItemPriority `xml:"priority"`

	ImagePath *oval_sc.EntityItemStringType `xml:"image_path"`

	CurrentDir *oval_sc.EntityItemStringType `xml:"current_dir"`

	CreationTime *oval_sc.EntityItemIntType `xml:"creation_time"`

	DepEnabled *oval_sc.EntityItemBoolType `xml:"dep_enabled"`

	PrimaryWindowText *oval_sc.EntityItemStringType `xml:"primary_window_text"`

	Name *oval_sc.EntityItemStringType `xml:"name"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type RegistryItem struct {
	XMLName xml.Name `xml:registry_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Hive *EntityItemRegistryHiveType `xml:"hive"`

	Key *oval_sc.EntityItemStringType `xml:"key"`

	Name *oval_sc.EntityItemStringType `xml:"name"`

	LastWriteTime *oval_sc.EntityItemIntType `xml:"last_write_time"`

	Type *EntityItemRegistryTypeType `xml:"type"`

	Value []oval_sc.EntityItemAnySimpleType `xml:"value"`

	ExpandedValue *oval_sc.EntityItemAnySimpleType `xml:"expanded_value"`

	WindowsView *EntityItemWindowsViewType `xml:"windows_view"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type RegkeyauditedpermissionsItem struct {
	XMLName xml.Name `xml:regkeyauditedpermissions_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Hive *EntityItemRegistryHiveType `xml:"hive"`

	Key *oval_sc.EntityItemStringType `xml:"key"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	TrusteeName *oval_sc.EntityItemStringType `xml:"trustee_name"`

	StandardDelete *EntityItemAuditType `xml:"standard_delete"`

	StandardReadControl *EntityItemAuditType `xml:"standard_read_control"`

	StandardWriteDac *EntityItemAuditType `xml:"standard_write_dac"`

	StandardWriteOwner *EntityItemAuditType `xml:"standard_write_owner"`

	StandardSynchronize *EntityItemAuditType `xml:"standard_synchronize"`

	AccessSystemSecurity *EntityItemAuditType `xml:"access_system_security"`

	GenericRead *EntityItemAuditType `xml:"generic_read"`

	GenericWrite *EntityItemAuditType `xml:"generic_write"`

	GenericExecute *EntityItemAuditType `xml:"generic_execute"`

	GenericAll *EntityItemAuditType `xml:"generic_all"`

	KeyQueryValue *EntityItemAuditType `xml:"key_query_value"`

	KeySetValue *EntityItemAuditType `xml:"key_set_value"`

	KeyCreateSubKey *EntityItemAuditType `xml:"key_create_sub_key"`

	KeyEnumerateSubKeys *EntityItemAuditType `xml:"key_enumerate_sub_keys"`

	KeyNotify *EntityItemAuditType `xml:"key_notify"`

	KeyCreateLink *EntityItemAuditType `xml:"key_create_link"`

	KeyWow6464key *EntityItemAuditType `xml:"key_wow64_64key"`

	KeyWow6432key *EntityItemAuditType `xml:"key_wow64_32key"`

	KeyWow64Res *EntityItemAuditType `xml:"key_wow64_res"`

	WindowsView *EntityItemWindowsViewType `xml:"windows_view"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type RegkeyeffectiverightsItem struct {
	XMLName xml.Name `xml:regkeyeffectiverights_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Hive *EntityItemRegistryHiveType `xml:"hive"`

	Key *oval_sc.EntityItemStringType `xml:"key"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	TrusteeName *oval_sc.EntityItemStringType `xml:"trustee_name"`

	StandardDelete *oval_sc.EntityItemBoolType `xml:"standard_delete"`

	StandardReadControl *oval_sc.EntityItemBoolType `xml:"standard_read_control"`

	StandardWriteDac *oval_sc.EntityItemBoolType `xml:"standard_write_dac"`

	StandardWriteOwner *oval_sc.EntityItemBoolType `xml:"standard_write_owner"`

	StandardSynchronize *oval_sc.EntityItemBoolType `xml:"standard_synchronize"`

	AccessSystemSecurity *oval_sc.EntityItemBoolType `xml:"access_system_security"`

	GenericRead *oval_sc.EntityItemBoolType `xml:"generic_read"`

	GenericWrite *oval_sc.EntityItemBoolType `xml:"generic_write"`

	GenericExecute *oval_sc.EntityItemBoolType `xml:"generic_execute"`

	GenericAll *oval_sc.EntityItemBoolType `xml:"generic_all"`

	KeyQueryValue *oval_sc.EntityItemBoolType `xml:"key_query_value"`

	KeySetValue *oval_sc.EntityItemBoolType `xml:"key_set_value"`

	KeyCreateSubKey *oval_sc.EntityItemBoolType `xml:"key_create_sub_key"`

	KeyEnumerateSubKeys *oval_sc.EntityItemBoolType `xml:"key_enumerate_sub_keys"`

	KeyNotify *oval_sc.EntityItemBoolType `xml:"key_notify"`

	KeyCreateLink *oval_sc.EntityItemBoolType `xml:"key_create_link"`

	KeyWow6464key *oval_sc.EntityItemBoolType `xml:"key_wow64_64key"`

	KeyWow6432key *oval_sc.EntityItemBoolType `xml:"key_wow64_32key"`

	KeyWow64Res *oval_sc.EntityItemBoolType `xml:"key_wow64_res"`

	WindowsView *EntityItemWindowsViewType `xml:"windows_view"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type ServiceItem struct {
	XMLName xml.Name `xml:service_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	ServiceName *oval_sc.EntityItemStringType `xml:"service_name"`

	DisplayName *oval_sc.EntityItemStringType `xml:"display_name"`

	Description *oval_sc.EntityItemStringType `xml:"description"`

	ServiceType []EntityItemServiceTypeType `xml:"service_type"`

	StartType *EntityItemServiceStartTypeType `xml:"start_type"`

	CurrentState *EntityItemServiceCurrentStateType `xml:"current_state"`

	ControlsAccepted []EntityItemServiceControlsAcceptedType `xml:"controls_accepted"`

	StartName *oval_sc.EntityItemStringType `xml:"start_name"`

	Path *oval_sc.EntityItemStringType `xml:"path"`

	Pid *oval_sc.EntityItemIntType `xml:"pid"`

	ServiceFlag *oval_sc.EntityItemBoolType `xml:"service_flag"`

	Dependencies []oval_sc.EntityItemStringType `xml:"dependencies"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type ServiceeffectiverightsItem struct {
	XMLName xml.Name `xml:serviceeffectiverights_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	ServiceName *oval_sc.EntityItemStringType `xml:"service_name"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	StandardDelete *oval_sc.EntityItemBoolType `xml:"standard_delete"`

	StandardReadControl *oval_sc.EntityItemBoolType `xml:"standard_read_control"`

	StandardWriteDac *oval_sc.EntityItemBoolType `xml:"standard_write_dac"`

	StandardWriteOwner *oval_sc.EntityItemBoolType `xml:"standard_write_owner"`

	GenericRead *oval_sc.EntityItemBoolType `xml:"generic_read"`

	GenericWrite *oval_sc.EntityItemBoolType `xml:"generic_write"`

	GenericExecute *oval_sc.EntityItemBoolType `xml:"generic_execute"`

	ServiceQueryConf *oval_sc.EntityItemBoolType `xml:"service_query_conf"`

	ServiceChangeConf *oval_sc.EntityItemBoolType `xml:"service_change_conf"`

	ServiceQueryStat *oval_sc.EntityItemBoolType `xml:"service_query_stat"`

	ServiceEnumDependents *oval_sc.EntityItemBoolType `xml:"service_enum_dependents"`

	ServiceStart *oval_sc.EntityItemBoolType `xml:"service_start"`

	ServiceStop *oval_sc.EntityItemBoolType `xml:"service_stop"`

	ServicePause *oval_sc.EntityItemBoolType `xml:"service_pause"`

	ServiceInterrogate *oval_sc.EntityItemBoolType `xml:"service_interrogate"`

	ServiceUserDefined *oval_sc.EntityItemBoolType `xml:"service_user_defined"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type SharedresourceItem struct {
	XMLName xml.Name `xml:sharedresource_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Netname *oval_sc.EntityItemStringType `xml:"netname"`

	SharedType *EntityItemSharedResourceTypeType `xml:"shared_type"`

	MaxUses *oval_sc.EntityItemIntType `xml:"max_uses"`

	CurrentUses *oval_sc.EntityItemIntType `xml:"current_uses"`

	LocalPath *oval_sc.EntityItemStringType `xml:"local_path"`

	AccessReadPermission *oval_sc.EntityItemBoolType `xml:"access_read_permission"`

	AccessWritePermission *oval_sc.EntityItemBoolType `xml:"access_write_permission"`

	AccessCreatePermission *oval_sc.EntityItemBoolType `xml:"access_create_permission"`

	AccessExecPermission *oval_sc.EntityItemBoolType `xml:"access_exec_permission"`

	AccessDeletePermission *oval_sc.EntityItemBoolType `xml:"access_delete_permission"`

	AccessAtribPermission *oval_sc.EntityItemBoolType `xml:"access_atrib_permission"`

	AccessPermPermission *oval_sc.EntityItemBoolType `xml:"access_perm_permission"`

	AccessAllPermission *oval_sc.EntityItemBoolType `xml:"access_all_permission"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type SharedresourceauditedpermissionsItem struct {
	XMLName xml.Name `xml:sharedresourceauditedpermissions_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Netname *oval_sc.EntityItemStringType `xml:"netname"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	StandardDelete *EntityItemAuditType `xml:"standard_delete"`

	StandardReadControl *EntityItemAuditType `xml:"standard_read_control"`

	StandardWriteDac *EntityItemAuditType `xml:"standard_write_dac"`

	StandardWriteOwner *EntityItemAuditType `xml:"standard_write_owner"`

	StandardSynchronize *EntityItemAuditType `xml:"standard_synchronize"`

	AccessSystemSecurity *EntityItemAuditType `xml:"access_system_security"`

	GenericRead *EntityItemAuditType `xml:"generic_read"`

	GenericWrite *EntityItemAuditType `xml:"generic_write"`

	GenericExecute *EntityItemAuditType `xml:"generic_execute"`

	GenericAll *EntityItemAuditType `xml:"generic_all"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type SharedresourceeffectiverightsItem struct {
	XMLName xml.Name `xml:sharedresourceeffectiverights_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Netname *oval_sc.EntityItemStringType `xml:"netname"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	StandardDelete *oval_sc.EntityItemBoolType `xml:"standard_delete"`

	StandardReadControl *oval_sc.EntityItemBoolType `xml:"standard_read_control"`

	StandardWriteDac *oval_sc.EntityItemBoolType `xml:"standard_write_dac"`

	StandardWriteOwner *oval_sc.EntityItemBoolType `xml:"standard_write_owner"`

	StandardSynchronize *oval_sc.EntityItemBoolType `xml:"standard_synchronize"`

	AccessSystemSecurity *oval_sc.EntityItemBoolType `xml:"access_system_security"`

	GenericRead *oval_sc.EntityItemBoolType `xml:"generic_read"`

	GenericWrite *oval_sc.EntityItemBoolType `xml:"generic_write"`

	GenericExecute *oval_sc.EntityItemBoolType `xml:"generic_execute"`

	GenericAll *oval_sc.EntityItemBoolType `xml:"generic_all"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type SidItem struct {
	XMLName xml.Name `xml:sid_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	TrusteeName *oval_sc.EntityItemStringType `xml:"trustee_name"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	TrusteeDomain *oval_sc.EntityItemStringType `xml:"trustee_domain"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type SidSidItem struct {
	XMLName xml.Name `xml:sid_sid_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	TrusteeName *oval_sc.EntityItemStringType `xml:"trustee_name"`

	TrusteeDomain *oval_sc.EntityItemStringType `xml:"trustee_domain"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type SystemmetricItem struct {
	XMLName xml.Name `xml:systemmetric_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Index *EntityItemSystemMetricIndexType `xml:"index"`

	Value *oval_sc.EntityItemIntType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type UacItem struct {
	XMLName xml.Name `xml:uac_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	AdminApprovalMode *oval_sc.EntityItemBoolType `xml:"admin_approval_mode"`

	ElevationPromptAdmin *oval_sc.EntityItemStringType `xml:"elevation_prompt_admin"`

	ElevationPromptStandard *oval_sc.EntityItemStringType `xml:"elevation_prompt_standard"`

	DetectInstallations *oval_sc.EntityItemBoolType `xml:"detect_installations"`

	ElevateSignedExecutables *oval_sc.EntityItemBoolType `xml:"elevate_signed_executables"`

	ElevateUiaccess *oval_sc.EntityItemBoolType `xml:"elevate_uiaccess"`

	RunAdminsAam *oval_sc.EntityItemBoolType `xml:"run_admins_aam"`

	SecureDesktop *oval_sc.EntityItemBoolType `xml:"secure_desktop"`

	VirtualizeWriteFailures *oval_sc.EntityItemBoolType `xml:"virtualize_write_failures"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type UserItem struct {
	XMLName xml.Name `xml:user_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	User *oval_sc.EntityItemStringType `xml:"user"`

	Enabled *oval_sc.EntityItemBoolType `xml:"enabled"`

	Group []oval_sc.EntityItemStringType `xml:"group"`

	LastLogon *oval_sc.EntityItemIntType `xml:"last_logon"`

	FullName *oval_sc.EntityItemStringType `xml:"full_name"`

	Comment *oval_sc.EntityItemStringType `xml:"comment"`

	PasswordAgeDays *oval_sc.EntityItemIntType `xml:"password_age_days"`

	Lockout *oval_sc.EntityItemBoolType `xml:"lockout"`

	PasswdNotreqd *oval_sc.EntityItemBoolType `xml:"passwd_notreqd"`

	DontExpirePasswd *oval_sc.EntityItemBoolType `xml:"dont_expire_passwd"`

	EncryptedTextPasswordAllowed *oval_sc.EntityItemBoolType `xml:"encrypted_text_password_allowed"`

	NotDelegated *oval_sc.EntityItemBoolType `xml:"not_delegated"`

	UseDesKeyOnly *oval_sc.EntityItemBoolType `xml:"use_des_key_only"`

	DontRequirePreauth *oval_sc.EntityItemBoolType `xml:"dont_require_preauth"`

	PasswordExpired *oval_sc.EntityItemBoolType `xml:"password_expired"`

	SmartcardRequired *oval_sc.EntityItemBoolType `xml:"smartcard_required"`

	TrustedForDelegation *oval_sc.EntityItemBoolType `xml:"trusted_for_delegation"`

	TrustedToAuthenticateForDelegation *oval_sc.EntityItemBoolType `xml:"trusted_to_authenticate_for_delegation"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type UserSidItem struct {
	XMLName xml.Name `xml:user_sid_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	UserSid *oval_sc.EntityItemStringType `xml:"user_sid"`

	Enabled *oval_sc.EntityItemBoolType `xml:"enabled"`

	GroupSid []oval_sc.EntityItemStringType `xml:"group_sid"`

	LastLogon *oval_sc.EntityItemIntType `xml:"last_logon"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type UserrightItem struct {
	XMLName xml.Name `xml:userright_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Userright *EntityItemUserRightType `xml:"userright"`

	TrusteeName *oval_sc.EntityItemStringType `xml:"trustee_name"`

	TrusteeSid *oval_sc.EntityItemStringType `xml:"trustee_sid"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type VolumeItem struct {
	XMLName xml.Name `xml:volume_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Rootpath *oval_sc.EntityItemStringType `xml:"rootpath"`

	FileSystem *oval_sc.EntityItemStringType `xml:"file_system"`

	Name *oval_sc.EntityItemStringType `xml:"name"`

	DriveType *EntityItemDriveTypeType `xml:"drive_type"`

	VolumeMaxComponentLength *oval_sc.EntityItemIntType `xml:"volume_max_component_length"`

	SerialNumber *oval_sc.EntityItemIntType `xml:"serial_number"`

	FileCaseSensitiveSearch *oval_sc.EntityItemBoolType `xml:"file_case_sensitive_search"`

	FileCasePreservedNames *oval_sc.EntityItemBoolType `xml:"file_case_preserved_names"`

	FileUnicodeOnDisk *oval_sc.EntityItemBoolType `xml:"file_unicode_on_disk"`

	FilePersistentAcls *oval_sc.EntityItemBoolType `xml:"file_persistent_acls"`

	FileFileCompression *oval_sc.EntityItemBoolType `xml:"file_file_compression"`

	FileVolumeQuotas *oval_sc.EntityItemBoolType `xml:"file_volume_quotas"`

	FileSupportsSparseFiles *oval_sc.EntityItemBoolType `xml:"file_supports_sparse_files"`

	FileSupportsReparsePoints *oval_sc.EntityItemBoolType `xml:"file_supports_reparse_points"`

	FileSupportsRemoteStorage *oval_sc.EntityItemBoolType `xml:"file_supports_remote_storage"`

	FileVolumeIsCompressed *oval_sc.EntityItemBoolType `xml:"file_volume_is_compressed"`

	FileSupportsObjectIds *oval_sc.EntityItemBoolType `xml:"file_supports_object_ids"`

	FileSupportsEncryption *oval_sc.EntityItemBoolType `xml:"file_supports_encryption"`

	FileNamedStreams *oval_sc.EntityItemBoolType `xml:"file_named_streams"`

	FileReadOnlyVolume *oval_sc.EntityItemBoolType `xml:"file_read_only_volume"`

	FileSequentialWriteOnce *oval_sc.EntityItemBoolType `xml:"file_sequential_write_once"`

	FileSupportsTransactions *oval_sc.EntityItemBoolType `xml:"file_supports_transactions"`

	FileSupportsHardLinks *oval_sc.EntityItemBoolType `xml:"file_supports_hard_links"`

	FileSupportsExtendedAttributes *oval_sc.EntityItemBoolType `xml:"file_supports_extended_attributes"`

	FileSupportsOpenByFileId *oval_sc.EntityItemBoolType `xml:"file_supports_open_by_file_id"`

	FileSupportsUsnJournal *oval_sc.EntityItemBoolType `xml:"file_supports_usn_journal"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type WmiItem struct {
	XMLName xml.Name `xml:wmi_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Namespace *oval_sc.EntityItemStringType `xml:"namespace"`

	Wql *oval_sc.EntityItemStringType `xml:"wql"`

	Result []oval_sc.EntityItemAnySimpleType `xml:"result"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type Wmi57Item struct {
	XMLName xml.Name `xml:wmi57_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Namespace *oval_sc.EntityItemStringType `xml:"namespace"`

	Wql *oval_sc.EntityItemStringType `xml:"wql"`

	Result []oval_sc.EntityItemRecordType `xml:"result"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type WuaupdatesearcherItem struct {
	XMLName xml.Name `xml:wuaupdatesearcher_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	SearchCriteria *oval_sc.EntityItemStringType `xml:"search_criteria"`

	UpdateId []oval_sc.EntityItemStringType `xml:"update_id"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type FileItemProductVersion struct {
	XMLName xml.Name `xml:product_version`
}

// Element
type ProcessItemPriority struct {
	XMLName xml.Name `xml:priority`
}

// XSD ComplexType declarations

type EntityItemAddrTypeType struct {
}

type EntityItemAdstypeType struct {
}

type EntityItemAuditType struct {
}

type EntityItemDriveTypeType struct {
}

type EntityItemFileTypeType struct {
}

type EntityItemFileAttributeType struct {
}

type EntityItemInterfaceTypeType struct {
}

type EntityItemNamingContextType struct {
}

type EntityItemNTUserAccountTypeType struct {
}

type EntityItemPeTargetMachineType struct {
}

type EntityItemPeSubsystemType struct {
}

type EntityItemProtocolType struct {
}

type EntityItemRegistryHiveType struct {
}

type EntityItemRegistryTypeType struct {
}

type EntityItemServiceControlsAcceptedType struct {
}

type EntityItemServiceCurrentStateType struct {
}

type EntityItemServiceStartTypeType struct {
}

type EntityItemServiceTypeType struct {
}

type EntityItemSharedResourceTypeType struct {
}

type EntityItemSystemMetricIndexType struct {
}

type EntityItemGUIDType struct {
}

type EntityItemCmdletVerbType struct {
}

type EntityItemWindowsViewType struct {
}

type EntityItemUserRightType struct {
}
