// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-system-characteristics-5
package oval_sc

import (
	"encoding/xml"
	"github.com/complianceascode/librescap/pkg/scap/models/oval"
	"github.com/complianceascode/librescap/pkg/scap/models/xml_dsig"
)

// Element
type OvalSystemCharacteristics struct {
	XMLName xml.Name `xml:oval_system_characteristics`

	Generator oval.GeneratorType `xml:"generator"`

	SystemInfo SystemInfoType `xml:"system_info"`

	CollectedObjects *CollectedObjectsType `xml:"collected_objects"`

	SystemData *SystemDataType `xml:"system_data"`

	Signature *xml_dsig.Signature `xml:"Signature"`
}

// Element
type Item struct {
	XMLName xml.Name `xml:item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Message []oval.MessageType `xml:"message"`
}

// XSD ComplexType declarations

type SystemInfoType struct {
	OsName string `xml:"os_name"`

	OsVersion string `xml:"os_version"`

	Architecture string `xml:"architecture"`

	PrimaryHostName string `xml:"primary_host_name"`

	Interfaces InterfacesType `xml:"interfaces"`
}

type InterfacesType struct {
	Interface []InterfaceType `xml:"interface"`
}

type InterfaceType struct {
	InterfaceName string `xml:"interface_name"`

	IpAddress string `xml:"ip_address"`

	MacAddress string `xml:"mac_address"`
}

type CollectedObjectsType struct {
	Object []ObjectType `xml:"object"`
}

type ObjectType struct {
	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	VariableInstance string `xml:"variable_instance,attr"`

	Comment string `xml:"comment,attr"`

	Flag string `xml:"flag,attr"`

	Message []oval.MessageType `xml:"message"`

	VariableValue []VariableValueType `xml:"variable_value"`

	Reference []ReferenceType `xml:"reference"`
}

type VariableValueType struct {
	VariableId string `xml:"variable_id,attr"`

	Text string `xml:",chardata"`
}

type ReferenceType struct {
	ItemRef string `xml:"item_ref,attr"`
}

type SystemDataType struct {
	Item []Item `xml:"item"`
}

type ItemType struct {
	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Message []oval.MessageType `xml:"message"`
}

type EntityItemSimpleBaseType struct {
	Text string `xml:",chardata"`
}

type EntityItemComplexBaseType struct {
}

type EntityItemIPAddressType struct {
}

type EntityItemIPAddressStringType struct {
}

type EntityItemAnySimpleType struct {
}

type EntityItemBinaryType struct {
}

type EntityItemBoolType struct {
}

type EntityItemFloatType struct {
}

type EntityItemIntType struct {
}

type EntityItemStringType struct {
}

type EntityItemRecordType struct {
	Field []EntityItemFieldType `xml:"field"`
}

type EntityItemFieldType struct {
	Name string `xml:"name,attr"`

	Text string `xml:",chardata"`
}

type EntityItemVersionType struct {
}

type EntityItemFilesetRevisionType struct {
}

type EntityItemIOSVersionType struct {
}

type EntityItemEVRStringType struct {
}

type EntityItemDebianEVRStringType struct {
}
