// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-definitions-5
package oval_def

import (
	"encoding/xml"
	"github.com/complianceascode/librescap/pkg/scap/models/oval"
	"github.com/complianceascode/librescap/pkg/scap/models/xml_dsig"
)

// Element
type OvalDefinitions struct {
	XMLName xml.Name `xml:oval_definitions`

	Generator oval.GeneratorType `xml:"generator"`

	Definitions *DefinitionsType `xml:"definitions"`

	Tests *TestsType `xml:"tests"`

	Objects *ObjectsType `xml:"objects"`

	States *StatesType `xml:"states"`

	Variables *VariablesType `xml:"variables"`

	Signature *xml_dsig.Signature `xml:"Signature"`
}

// Element
type Notes struct {
	XMLName xml.Name `xml:notes`

	Note []string `xml:"note"`
}

// Element
type Definition struct {
	XMLName xml.Name `xml:definition`

	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Class string `xml:"class,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Metadata MetadataType `xml:"metadata"`

	Notes *oval.Notes `xml:"notes"`

	Criteria *CriteriaType `xml:"criteria"`
}

// Element
type Test struct {
	XMLName xml.Name `xml:test`

	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	CheckExistence string `xml:"check_existence,attr"`

	Check string `xml:"check,attr"`

	StateOperator string `xml:"state_operator,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

// Element
type Object struct {
	XMLName xml.Name `xml:object`

	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

// Element
type Set struct {
	XMLName xml.Name `xml:set`

	SetOperator string `xml:"set_operator,attr"`
}

// Element
type Filter struct {
	XMLName xml.Name `xml:filter`

	Action string `xml:"action,attr"`

	Text string `xml:",chardata"`
}

// Element
type State struct {
	XMLName xml.Name `xml:state`

	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Operator string `xml:"operator,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

// Element
type Variable struct {
	XMLName xml.Name `xml:variable`

	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Datatype string `xml:"datatype,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

// Element
type ExternalVariable struct {
	XMLName xml.Name `xml:external_variable`

	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Datatype string `xml:"datatype,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

// Element
type ConstantVariable struct {
	XMLName xml.Name `xml:constant_variable`

	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Datatype string `xml:"datatype,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Value []ValueType `xml:"value"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

// Element
type LocalVariable struct {
	XMLName xml.Name `xml:local_variable`

	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Datatype string `xml:"datatype,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

// XSD ComplexType declarations

type DefinitionsType struct {
	Definition []Definition `xml:"definition"`
}

type DefinitionType struct {
	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Class string `xml:"class,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Metadata MetadataType `xml:"metadata"`

	Notes *oval.Notes `xml:"notes"`

	Criteria *CriteriaType `xml:"criteria"`
}

type MetadataType struct {
	Title string `xml:"title"`

	Affected []AffectedType `xml:"affected"`

	Reference []ReferenceType `xml:"reference"`

	Description string `xml:"description"`
}

type AffectedType struct {
	Family string `xml:"family,attr"`

	Platform []string `xml:"platform"`

	Product []string `xml:"product"`
}

type ReferenceType struct {
	Source string `xml:"source,attr"`

	RefId string `xml:"ref_id,attr"`

	RefUrl string `xml:"ref_url,attr"`
}

type CriteriaType struct {
	ApplicabilityCheck string `xml:"applicability_check,attr"`

	Operator string `xml:"operator,attr"`

	Negate string `xml:"negate,attr"`

	Comment string `xml:"comment,attr"`

	Criteria []CriteriaType `xml:"criteria"`

	Criterion []CriterionType `xml:"criterion"`

	ExtendDefinition []ExtendDefinitionType `xml:"extend_definition"`
}

type CriterionType struct {
	ApplicabilityCheck string `xml:"applicability_check,attr"`

	TestRef string `xml:"test_ref,attr"`

	Negate string `xml:"negate,attr"`

	Comment string `xml:"comment,attr"`
}

type ExtendDefinitionType struct {
	ApplicabilityCheck string `xml:"applicability_check,attr"`

	DefinitionRef string `xml:"definition_ref,attr"`

	Negate string `xml:"negate,attr"`

	Comment string `xml:"comment,attr"`
}

type TestsType struct {
	Test []Test `xml:"test"`
}

type TestType struct {
	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	CheckExistence string `xml:"check_existence,attr"`

	Check string `xml:"check,attr"`

	StateOperator string `xml:"state_operator,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

type ObjectRefType struct {
	ObjectRef string `xml:"object_ref,attr"`
}

type StateRefType struct {
	StateRef string `xml:"state_ref,attr"`
}

type ObjectsType struct {
	Object []Object `xml:"object"`
}

type ObjectType struct {
	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

type StatesType struct {
	State []State `xml:"state"`
}

type StateType struct {
	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Operator string `xml:"operator,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

type VariablesType struct {
	Variable []Variable `xml:"variable"`
}

type VariableType struct {
	Id string `xml:"id,attr"`

	Version string `xml:"version,attr"`

	Datatype string `xml:"datatype,attr"`

	Comment string `xml:"comment,attr"`

	Deprecated string `xml:"deprecated,attr"`

	Signature *xml_dsig.Signature `xml:"Signature"`

	Notes *oval.Notes `xml:"notes"`
}

type PossibleValueType struct {
	Hint string `xml:"hint,attr"`

	Text string `xml:",chardata"`
}

type PossibleRestrictionType struct {
	Operator string `xml:"operator,attr"`

	Hint string `xml:"hint,attr"`

	Restriction []RestrictionType `xml:"restriction"`
}

type RestrictionType struct {
	Operation string `xml:"operation,attr"`

	Text string `xml:",chardata"`
}

type ValueType struct {
	Text string `xml:",chardata"`
}

type LiteralComponentType struct {
	Datatype string `xml:"datatype,attr"`

	Text string `xml:",chardata"`
}

type ObjectComponentType struct {
	ObjectRef string `xml:"object_ref,attr"`

	ItemField string `xml:"item_field,attr"`

	RecordField string `xml:"record_field,attr"`
}

type VariableComponentType struct {
	VarRef string `xml:"var_ref,attr"`
}

type ArithmeticFunctionType struct {
	ArithmeticOperation string `xml:"arithmetic_operation,attr"`
}

type BeginFunctionType struct {
	Character string `xml:"character,attr"`
}

type ConcatFunctionType struct {
}

type EndFunctionType struct {
	Character string `xml:"character,attr"`
}

type EscapeRegexFunctionType struct {
}

type SplitFunctionType struct {
	Delimiter string `xml:"delimiter,attr"`
}

type SubstringFunctionType struct {
	SubstringStart string `xml:"substring_start,attr"`

	SubstringLength string `xml:"substring_length,attr"`
}

type TimeDifferenceFunctionType struct {
	Format1 string `xml:"format_1,attr"`

	Format2 string `xml:"format_2,attr"`
}

type RegexCaptureFunctionType struct {
	Pattern string `xml:"pattern,attr"`
}

type UniqueFunctionType struct {
}

type CountFunctionType struct {
}

type GlobToRegexFunctionType struct {
	GlobNoescape string `xml:"glob_noescape,attr"`
}

type EntitySimpleBaseType struct {
	Text string `xml:",chardata"`
}

type EntityComplexBaseType struct {
}

type EntityObjectIPAddressType struct {
}

type EntityObjectIPAddressStringType struct {
}

type EntityObjectAnySimpleType struct {
}

type EntityObjectBinaryType struct {
}

type EntityObjectBoolType struct {
}

type EntityObjectFloatType struct {
}

type EntityObjectIntType struct {
}

type EntityObjectStringType struct {
}

type EntityObjectVersionType struct {
}

type EntityObjectRecordType struct {
	Field []EntityObjectFieldType `xml:"field"`
}

type EntityObjectFieldType struct {
	Name string `xml:"name,attr"`

	EntityCheck string `xml:"entity_check,attr"`

	Text string `xml:",chardata"`
}

type EntityStateSimpleBaseType struct {
	EntityCheck string `xml:"entity_check,attr"`

	CheckExistence string `xml:"check_existence,attr"`

	Text string `xml:",chardata"`
}

type EntityStateComplexBaseType struct {
	EntityCheck string `xml:"entity_check,attr"`

	CheckExistence string `xml:"check_existence,attr"`
}

type EntityStateIPAddressType struct {
}

type EntityStateIPAddressStringType struct {
}

type EntityStateAnySimpleType struct {
}

type EntityStateBinaryType struct {
}

type EntityStateBoolType struct {
}

type EntityStateFloatType struct {
}

type EntityStateIntType struct {
}

type EntityStateEVRStringType struct {
}

type EntityStateDebianEVRStringType struct {
}

type EntityStateVersionType struct {
}

type EntityStateFileSetRevisionType struct {
}

type EntityStateIOSVersionType struct {
}

type EntityStateStringType struct {
}

type EntityStateRecordType struct {
	EntityCheck string `xml:"entity_check,attr"`

	CheckExistence string `xml:"check_existence,attr"`

	Field []EntityStateFieldType `xml:"field"`
}

type EntityStateFieldType struct {
	Name string `xml:"name,attr"`

	EntityCheck string `xml:"entity_check,attr"`

	Text string `xml:",chardata"`
}
