// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://www.w3.org/1999/xlink
package xlink

import (
	"encoding/xml"
)

// Element
type Title struct {
	XMLName xml.Name `xml:title`
}

// Element
type Resource struct {
	XMLName xml.Name `xml:resource`
}

// Element
type Locator struct {
	XMLName xml.Name `xml:locator`
}

// Element
type Arc struct {
	XMLName xml.Name `xml:arc`
}

// XSD ComplexType declarations

type Simple struct {
	InnerXml string `xml:",innerxml"`
}

type Extended struct {
}

type TitleEltType struct {
	InnerXml string `xml:",innerxml"`
}

type ResourceType struct {
	InnerXml string `xml:",innerxml"`
}

type LocatorType struct {
}

type ArcType struct {
}
