// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#apache
package apache_sc

import (
	"encoding/xml"
	"github.com/complianceascode/librescap/pkg/scap/models/oval"
	"github.com/complianceascode/librescap/pkg/scap/models/oval_sc"
)

// Element
type HttpdItem struct {
	XMLName xml.Name `xml:httpd_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Path *oval_sc.EntityItemStringType `xml:"path"`

	BinaryName *oval_sc.EntityItemStringType `xml:"binary_name"`

	Version *oval_sc.EntityItemVersionType `xml:"version"`

	Message []oval.MessageType `xml:"message"`
}

// XSD ComplexType declarations
