// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#esx
package esx_sc

import (
	"encoding/xml"
	"github.com/complianceascode/librescap/pkg/scap/models/oval"
	"github.com/complianceascode/librescap/pkg/scap/models/oval_sc"
)

// Element
type PatchItem struct {
	XMLName xml.Name `xml:patch_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	PatchNumber *oval_sc.EntityItemStringType `xml:"patch_number"`

	PatchName *oval_sc.EntityItemStringType `xml:"patch_name"`

	KnowledgeBaseId *oval_sc.EntityItemIntType `xml:"knowledge_base_id"`

	BundleId *oval_sc.EntityItemIntType `xml:"bundle_id"`

	Classification *EntityItemClassificationType `xml:"classification"`

	SupportLevel *EntityItemSupportLevelType `xml:"support_level"`

	StatusElm *oval_sc.EntityItemBoolType `xml:"status"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type VersionItem struct {
	XMLName xml.Name `xml:version_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Release *oval_sc.EntityItemVersionType `xml:"release"`

	Build *oval_sc.EntityItemIntType `xml:"build"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type VisdkmanagedobjectItem struct {
	XMLName xml.Name `xml:visdkmanagedobject_item`

	Id string `xml:"id,attr"`

	Status string `xml:"status,attr"`

	Property *oval_sc.EntityItemStringType `xml:"property"`

	Value []oval_sc.EntityItemAnySimpleType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// XSD ComplexType declarations

type EntityItemClassificationType struct {
}

type EntityItemSupportLevelType struct {
}
