name: LibreSCAP Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go-version: [1.13.x, 1.14.x]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Go dependencies
      run: go get -v -t -d ./...

    - name: Lint Go Code
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        make lint

    - name: Run Code Coverage
      run: make test-coverage

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}} ## https://github.com/ComplianceAsCode/libreSCAP/settings/secrets
        file: ./coverage.txt

    - name: Unit tests
      run: go test ./...

    - name: Build
      run: make build
